
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'MiniShopDb')
BEGIN
    ALTER DATABASE MiniShopDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE MiniShopDb;
END


CREATE DATABASE MiniShopDb;
GO