name: Frontend CI

on:
  push:
    branch: [main]
    paths:
      - 'MiniShop.UI/**'
  pull_request:
    paths:
      - 'MiniShop.UI/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd MiniShop.UI
          npm install

      - name: Build React
        run: |
          cd MiniShop.UI
          npm run build